# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 090b39cd453316f543fe69c98290a63aaab7d2519233386ba49fa6ba03126cca0a0342c0f8cb011d40e2df27ec1eece9afedc2ffab5fde1cbe3843353268383f

test:
  secret_key_base: ad5a7b959105cd8bd5c5bd2040a60bce366b3ff39e77053989ac25ab86327c1de8e0c37d8a2cb80a938d7512192e07c69a08f17f7eaabc467c3034bedff63787

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= File.read(File.expand_path("~/keys/secret_key_base")).strip %>
